environment:
  node_version: "8.9.1"

cache:
  - '%APPDATA%\npm-cache'

install:
  - ps: Install-Product node $env:node_version
  - npm install

build_script:
  - npm install
  - npm run vscode:prepublish

test_script:
  - node --version
  - npm --version
  - npm test --silent